<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Trending Top 10 on miniTV</name>
   <tag></tag>
   <elementGuidId>bdce22fc-3109-4cc0-b719-52ca97961f74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>872b9f35-7b6e-4887-84bc-5459e5148538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>home_thumbnailCarouselItem_1_carouselHeader</value>
      <webElementGuid>4aacf3a6-8f09-4fca-bc5e-35d19a3f1c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> Heading_h5__bn0Bc ThumbnailCarousel_title__1SnZd</value>
      <webElementGuid>6867cb5d-f6a3-48f0-b34b-92f84060141e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Trending Top 10 on miniTV</value>
      <webElementGuid>a4503fbc-4fb6-41e9-b556-086681567557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;infiniteScrollV3&quot;)/div[2]/div[@class=&quot;ThumbnailCarousel_container__PM9KN&quot;]/h2[@class=&quot;Heading_h5__bn0Bc ThumbnailCarousel_title__1SnZd&quot;]</value>
      <webElementGuid>52ecefd9-a821-47b5-9250-3b5bd903bdc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='']</value>
      <webElementGuid>0bbef36e-cb43-443d-a73e-c1380d559648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='infiniteScrollV3']/div[2]/div/h2</value>
      <webElementGuid>6be6979f-740c-4e24-98f1-ff56c9fc8b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>b1bf9f36-5a2f-439a-b081-2af5ff463162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Trending Top 10 on miniTV' or . = 'Trending Top 10 on miniTV')]</value>
      <webElementGuid>04e8384e-fa40-4d76-9435-0807f927700a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
